// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: pkg/players/proto/message.proto

package player_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Team int32

const (
	Team_CSK  Team = 0
	Team_MI   Team = 1
	Team_DC   Team = 2
	Team_PBKS Team = 3
	Team_KKR  Team = 4
	Team_RR   Team = 5
	Team_RCB  Team = 6
	Team_SRH  Team = 7
	Team_GT   Team = 8
	Team_LSG  Team = 9
)

// Enum value maps for Team.
var (
	Team_name = map[int32]string{
		0: "CSK",
		1: "MI",
		2: "DC",
		3: "PBKS",
		4: "KKR",
		5: "RR",
		6: "RCB",
		7: "SRH",
		8: "GT",
		9: "LSG",
	}
	Team_value = map[string]int32{
		"CSK":  0,
		"MI":   1,
		"DC":   2,
		"PBKS": 3,
		"KKR":  4,
		"RR":   5,
		"RCB":  6,
		"SRH":  7,
		"GT":   8,
		"LSG":  9,
	}
)

func (x Team) Enum() *Team {
	p := new(Team)
	*p = x
	return p
}

func (x Team) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Team) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_players_proto_message_proto_enumTypes[0].Descriptor()
}

func (Team) Type() protoreflect.EnumType {
	return &file_pkg_players_proto_message_proto_enumTypes[0]
}

func (x Team) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Team.Descriptor instead.
func (Team) EnumDescriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{0}
}

type PlayerType int32

const (
	PlayerType_WicketKeeper PlayerType = 0
	PlayerType_Batsman      PlayerType = 1
	PlayerType_AllRounder   PlayerType = 2
	PlayerType_Bowler       PlayerType = 3
)

// Enum value maps for PlayerType.
var (
	PlayerType_name = map[int32]string{
		0: "WicketKeeper",
		1: "Batsman",
		2: "AllRounder",
		3: "Bowler",
	}
	PlayerType_value = map[string]int32{
		"WicketKeeper": 0,
		"Batsman":      1,
		"AllRounder":   2,
		"Bowler":       3,
	}
)

func (x PlayerType) Enum() *PlayerType {
	p := new(PlayerType)
	*p = x
	return p
}

func (x PlayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_players_proto_message_proto_enumTypes[1].Descriptor()
}

func (PlayerType) Type() protoreflect.EnumType {
	return &file_pkg_players_proto_message_proto_enumTypes[1]
}

func (x PlayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerType.Descriptor instead.
func (PlayerType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{1}
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Team Team       `protobuf:"varint,2,opt,name=team,proto3,enum=player_pb.Team" json:"team,omitempty"`
	Type PlayerType `protobuf:"varint,3,opt,name=type,proto3,enum=player_pb.PlayerType" json:"type,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_players_proto_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_players_proto_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetTeam() Team {
	if x != nil {
		return x.Team
	}
	return Team_CSK
}

func (x *Player) GetType() PlayerType {
	if x != nil {
		return x.Type
	}
	return PlayerType_WicketKeeper
}

type ImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageType string `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_players_proto_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_players_proto_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

type TeamPlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  Team `protobuf:"varint,1,opt,name=first,proto3,enum=player_pb.Team" json:"first,omitempty"`
	Second Team `protobuf:"varint,2,opt,name=second,proto3,enum=player_pb.Team" json:"second,omitempty"`
}

func (x *TeamPlayerRequest) Reset() {
	*x = TeamPlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_players_proto_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamPlayerRequest) ProtoMessage() {}

func (x *TeamPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_players_proto_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamPlayerRequest.ProtoReflect.Descriptor instead.
func (*TeamPlayerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *TeamPlayerRequest) GetFirst() Team {
	if x != nil {
		return x.First
	}
	return Team_CSK
}

func (x *TeamPlayerRequest) GetSecond() Team {
	if x != nil {
		return x.Second
	}
	return Team_CSK
}

type TeamPlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  []*Player `protobuf:"bytes,1,rep,name=first,proto3" json:"first,omitempty"`
	Second []*Player `protobuf:"bytes,2,rep,name=second,proto3" json:"second,omitempty"`
}

func (x *TeamPlayerResponse) Reset() {
	*x = TeamPlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_players_proto_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamPlayerResponse) ProtoMessage() {}

func (x *TeamPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_players_proto_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamPlayerResponse.ProtoReflect.Descriptor instead.
func (*TeamPlayerResponse) Descriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *TeamPlayerResponse) GetFirst() []*Player {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *TeamPlayerResponse) GetSecond() []*Player {
	if x != nil {
		return x.Second
	}
	return nil
}

type UploadPlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadPlayersRequest) Reset() {
	*x = UploadPlayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_players_proto_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPlayersRequest) ProtoMessage() {}

func (x *UploadPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_players_proto_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPlayersRequest.ProtoReflect.Descriptor instead.
func (*UploadPlayersRequest) Descriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{4}
}

type UploadPlayersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *UploadPlayersResponse) Reset() {
	*x = UploadPlayersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_players_proto_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPlayersResponse) ProtoMessage() {}

func (x *UploadPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_players_proto_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPlayersResponse.ProtoReflect.Descriptor instead.
func (*UploadPlayersResponse) Descriptor() ([]byte, []int) {
	return file_pkg_players_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *UploadPlayersResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_pkg_players_proto_message_proto protoreflect.FileDescriptor

var file_pkg_players_proto_message_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x22, 0x6c, 0x0a, 0x06,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x65,
	0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x12,
	0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x09, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x63, 0x0a, 0x11, 0x54, 0x65, 0x61, 0x6d, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x2e, 0x54,
	0x65, 0x61, 0x6d, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x68, 0x0a, 0x12, 0x54,
	0x65, 0x61, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a,
	0x15, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x2a, 0x5d, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x53, 0x4b, 0x10,
	0x00, 0x12, 0x06, 0x0a, 0x02, 0x4d, 0x49, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x44, 0x43, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x42, 0x4b, 0x53, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x4b,
	0x4b, 0x52, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x52, 0x52, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03,
	0x52, 0x43, 0x42, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x52, 0x48, 0x10, 0x07, 0x12, 0x06,
	0x0a, 0x02, 0x47, 0x54, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x53, 0x47, 0x10, 0x09, 0x2a,
	0x47, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x0c, 0x57, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x42, 0x61, 0x74, 0x73, 0x6d, 0x61, 0x6e, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x6f, 0x77, 0x6c, 0x65, 0x72, 0x10, 0x03, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_players_proto_message_proto_rawDescOnce sync.Once
	file_pkg_players_proto_message_proto_rawDescData = file_pkg_players_proto_message_proto_rawDesc
)

func file_pkg_players_proto_message_proto_rawDescGZIP() []byte {
	file_pkg_players_proto_message_proto_rawDescOnce.Do(func() {
		file_pkg_players_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_players_proto_message_proto_rawDescData)
	})
	return file_pkg_players_proto_message_proto_rawDescData
}

var file_pkg_players_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_players_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_players_proto_message_proto_goTypes = []interface{}{
	(Team)(0),                     // 0: player_pb.Team
	(PlayerType)(0),               // 1: player_pb.PlayerType
	(*Player)(nil),                // 2: player_pb.Player
	(*ImageInfo)(nil),             // 3: player_pb.ImageInfo
	(*TeamPlayerRequest)(nil),     // 4: player_pb.TeamPlayerRequest
	(*TeamPlayerResponse)(nil),    // 5: player_pb.TeamPlayerResponse
	(*UploadPlayersRequest)(nil),  // 6: player_pb.UploadPlayersRequest
	(*UploadPlayersResponse)(nil), // 7: player_pb.UploadPlayersResponse
}
var file_pkg_players_proto_message_proto_depIdxs = []int32{
	0, // 0: player_pb.Player.team:type_name -> player_pb.Team
	1, // 1: player_pb.Player.type:type_name -> player_pb.PlayerType
	0, // 2: player_pb.TeamPlayerRequest.first:type_name -> player_pb.Team
	0, // 3: player_pb.TeamPlayerRequest.second:type_name -> player_pb.Team
	2, // 4: player_pb.TeamPlayerResponse.first:type_name -> player_pb.Player
	2, // 5: player_pb.TeamPlayerResponse.second:type_name -> player_pb.Player
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_players_proto_message_proto_init() }
func file_pkg_players_proto_message_proto_init() {
	if File_pkg_players_proto_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_players_proto_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_players_proto_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_players_proto_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamPlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_players_proto_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamPlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_players_proto_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPlayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_players_proto_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPlayersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_players_proto_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_players_proto_message_proto_goTypes,
		DependencyIndexes: file_pkg_players_proto_message_proto_depIdxs,
		EnumInfos:         file_pkg_players_proto_message_proto_enumTypes,
		MessageInfos:      file_pkg_players_proto_message_proto_msgTypes,
	}.Build()
	File_pkg_players_proto_message_proto = out.File
	file_pkg_players_proto_message_proto_rawDesc = nil
	file_pkg_players_proto_message_proto_goTypes = nil
	file_pkg_players_proto_message_proto_depIdxs = nil
}
